return {
  "CopilotC-Nvim/CopilotChat.nvim",
  dependencies = { "nvim-lua/plenary.nvim" },
  build = "make tiktoken",
  cond = MetaConfig.enable_all_plugins or MetaConfig.enable_copilot_plugins,
  keys = { { "<leader>a", function() require("CopilotChat").toggle() end, mode = { "n", "x" }, desc = "[A]I chat" } },
  opts = {
    mappings = {
      complete = { normal = "", insert = "" },
      close = { normal = "q", insert = "" },
      reset = { normal = "<localleader>r", insert = "" },
      submit_prompt = { normal = "<CR>", insert = "" },
      toggle_sticky = { normal = "<localleader>s", insert = "" },
      clear_stickies = { normal = "<localleader>x", insert = "" },
      accept_diff = { normal = "<localleader>a", insert = "" },
      jump_to_diff = { normal = "<localleader>j", insert = "" },
      quickfix_answers = { normal = "", insert = "" },
      quickfix_diffs = { normal = "", insert = "" },
      yank_diff = { normal = "<localleader>y" },
      show_diff = { normal = "<localleader>d" },
      show_info = { normal = "<localleader>i" },
      show_help = { normal = "g?" },
    },
  },
}
