return {
  "NeogitOrg/neogit",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "folke/snacks.nvim",
  },
  keys = { { "<leader>gm", function() require("neogit").open() end, desc = "[G]it: [M]enu" } },
  opts = {
    commit_editor = { spell_check = false },
    use_default_keymaps = false,
    integrations = { snacks = true },
    mappings = {
      commit_editor = {}, -- Prefer keymap definition in ./after/ftplugin/gitcommit.lua
      commit_editor_I = {},
      commit_view = {},
      rebase_editor = {}, -- Prefer keymap definition in ./after/ftplugin/gitrebase.lua
      rebase_editor_I = {},
      finder = {},
      popup = {
        ["?"] = "HelpPopup",
        ["C"] = "CherryPickPopup",
        ["d"] = "DiffPopup",
        ["p"] = "PushPopup",
        ["R"] = "ResetPopup",
        ["<M-s>"] = "StashPopup",
        ["i"] = "IgnorePopup",
        ["t"] = "TagPopup",
        ["b"] = "BranchPopup",
        ["B"] = "BisectPopup",
        ["w"] = "WorktreePopup",
        ["c"] = "CommitPopup",
        ["f"] = "FetchPopup",
        ["l"] = "LogPopup",
        ["m"] = "MergePopup",
        ["P"] = "PullPopup",
        ["r"] = "RebasePopup",
        ["<M-r>"] = "RevertPopup",
      },
      status = {
        ["j"] = "MoveDown",
        ["k"] = "MoveUp",
        ["o"] = "OpenTree",
        ["q"] = "Close",
        ["<Tab>"] = "Toggle",
        ["x"] = "Discard",
        ["s"] = "Stage",
        ["S"] = "StageAll",
        ["<C-s>"] = "StageUnstaged",
        ["u"] = "Unstage",
        ["<M-u>"] = "Untrack", -- <C-u> is left for scrolling
        ["U"] = "UnstageStaged",
        ["<C-r>"] = "RefreshBuffer",
        ["<CR>"] = "GoToFile",
        ["{"] = "GoToPreviousHunkHeader",
        ["}"] = "GoToNextHunkHeader",
        ["<C-n>"] = "NextSection",
        ["<C-p>"] = "PreviousSection",
      },
    },
  },
}
