-- Define snippets to create easily files and directories.
-- For some file types, some standard files which are often created from scratch (like `README.md`)
-- and not copy/pasted from somewhere else or generated by other tools (like `pyproject.toml`) are
-- available through choice snippets

local ls = require("luasnip")
local show_conds = require("luasnip.extras.conditions.show")

local custom_conds = require("plugins.core.luasnip.conditions")

local i = ls.insert_node
local c = ls.choice_node
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node

local is_in_empty_line = custom_conds.line_begin * show_conds.line_end

return {
  s({ trig = ".json", show_condition = is_in_empty_line }, { i(1, "name"), t(".json") }),
  s({ trig = ".json", show_condition = -is_in_empty_line }, { t(".json") }),

  s({ trig = ".lua", show_condition = custom_conds.project.is_lua * is_in_empty_line }, {
    c(1, {
      sn(nil, { i(1, "name"), t(".lua") }),
      t("init.lua"),
      t("temp.lua"),
    }),
  }),
  s({ trig = ".lua", show_condition = custom_conds.project.is_lua - is_in_empty_line }, { t(".lua") }),

  s({ trig = ".md", show_condition = is_in_empty_line }, {
    c(1, {
      sn(nil, { i(1, "name"), t(".md") }),
      t("README.md"),
      t("notes.md"),
    }),
  }),
  s({ trig = ".md", show_condition = -is_in_empty_line }, { t(".md") }),

  s({ trig = ".norg", show_condition = is_in_empty_line }, {
    c(1, {
      sn(nil, { i(1, "name"), t(".norg") }),
      t("todo.norg"),
    }),
  }),
  s({ trig = ".norg", show_condition = -is_in_empty_line }, { t(".norg") }),

  s({ trig = ".py", show_condition = custom_conds.project.is_python * is_in_empty_line }, {
    c(1, {
      sn(nil, { i(1, "name"), t(".py") }),
      t("__init__.py"),
      t("temp.py"),
    }),
  }),
  s({ trig = ".py", show_condition = custom_conds.project.is_python - is_in_empty_line }, { t(".py") }),

  s({ trig = ".sh", show_condition = is_in_empty_line }, { i(1, "name"), t(".sh") }),
  s({ trig = ".sh", show_condition = -is_in_empty_line }, { t(".sh") }),

  s({ trig = ".toml", show_condition = is_in_empty_line }, { i(1, "name"), t(".toml") }),
  s({ trig = ".toml", show_condition = -is_in_empty_line }, { t(".toml") }),

  s({ trig = ".yaml", show_condition = is_in_empty_line }, {
    c(1, {
      sn(nil, { i(1, "name"), t(".yaml") }),
      sn(nil, { i(1, "name"), t(".yml") }),
    }),
  }),
  s({ trig = ".yaml", show_condition = -is_in_empty_line }, { c(1, { t(".yaml"), t(".yml") }) }),

  s({ trig = ".zsh", show_condition = is_in_empty_line }, { i(1, "name"), t(".zsh") }),
  s({ trig = ".zsh", show_condition = -is_in_empty_line }, { t(".zsh") }),
}
